# Generated by Django 4.1.6 on 2023-02-16 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_static_pages', '0002_alter_staticpage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url-адрес')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('name',),
                'unique_together': {('name', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='заголовок')),
                ('text', models.TextField(blank=True, db_index=True, verbose_name='текст')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='дата публикации')),
                ('category', models.ManyToManyField(db_index=True, to='app_news.category', verbose_name='категории')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='NewsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=255, verbose_name='текст ссылки')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_static_pages.staticpage', verbose_name='ссылка на статическую страницу')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_news.news', verbose_name='новость')),
            ],
            options={
                'verbose_name': 'ссылка на статическую страницу',
                'verbose_name_plural': 'ссылки на статические страницы',
            },
        ),
    ]
