# Generated by Django 4.1.6 on 2023-02-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_news', '0002_news_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AddField(
            model_name='news',
            name='groups',
            field=models.ManyToManyField(db_index=True, to='auth.group', verbose_name='группы'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
