# Generated by Django 4.1.6 on 2023-02-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_remove_news_category_news_groups_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='groups',
        ),
        migrations.AddField(
            model_name='news',
            name='for_all',
            field=models.BooleanField(default=False, verbose_name='для всех – на странице «Заказы»'),
        ),
        migrations.AddField(
            model_name='news',
            name='for_contractors',
            field=models.BooleanField(default=False, verbose_name='для заказчиков в ЛК'),
        ),
        migrations.AddField(
            model_name='news',
            name='for_core',
            field=models.BooleanField(default=False, verbose_name='для участников ядра в ЛК'),
        ),
        migrations.AddField(
            model_name='news',
            name='for_freelancers',
            field=models.BooleanField(default=False, verbose_name='для фрилансеров в ЛК'),
        ),
        migrations.AddField(
            model_name='news',
            name='for_new_contractors',
            field=models.BooleanField(default=False, verbose_name='для новых заказчиков в ЛК'),
        ),
        migrations.AddField(
            model_name='news',
            name='for_new_freelancers',
            field=models.BooleanField(default=False, verbose_name='для новых фрилансеров в ЛК'),
        ),
        migrations.AddField(
            model_name='news',
            name='for_registered',
            field=models.BooleanField(default=False, verbose_name='для всех зарегистрированных пользователей в ЛК'),
        ),
    ]
