# Generated by Django 4.1.6 on 2023-02-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_survey', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='количество голосов'),
        ),
    ]
