# Generated by Django 4.1.6 on 2023-02-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_survey', '0003_choice_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_finished',
        ),
    ]
