# Generated by Django 4.1.6 on 2023-02-25 08:35

import app_portfolio.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_ads', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'], message='Ошибка загрузки: допускаются только файлы с расширением .jpg .png'), app_portfolio.validators.file_size_validate], verbose_name='обложка')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания')),
                ('corrected_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='дата изменения')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='стоимость')),
                ('price_currency', models.CharField(blank=True, choices=[('USD', '$'), ('RUB', '₽'), ('EUR', '€')], max_length=3, null=True, verbose_name='валюта')),
                ('time_spent', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='потрачено времени')),
                ('time_type', models.CharField(blank=True, choices=[('USD', '$'), ('RUB', '₽'), ('EUR', '€')], max_length=3, null=True, verbose_name='время')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='ссылка')),
                ('video', models.CharField(blank=True, max_length=255, null=True, verbose_name='видео')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активна')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='app_ads.category', verbose_name='категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'работа',
                'verbose_name_plural': 'работы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='portfolio/files/', validators=[app_portfolio.validators.file_size_validate], verbose_name='файл')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app_portfolio.work', verbose_name='работа')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлы',
            },
        ),
    ]
