# Generated by Django 4.1.6 on 2023-02-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time_type',
            field=models.CharField(blank=True, choices=[('h', 'в часах'), ('d', 'в днях'), ('m', 'в месяцах')], max_length=3, null=True, verbose_name='время'),
        ),
    ]
