# Generated by Django 4.1.6 on 2023-02-25 15:58

import app_portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0002_alter_work_time_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/files/', validators=[app_portfolio.validators.file_size_validate], verbose_name='файл1'),
        ),
        migrations.AddField(
            model_name='work',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/files/', validators=[app_portfolio.validators.file_size_validate], verbose_name='файл2'),
        ),
        migrations.AddField(
            model_name='work',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/files/', validators=[app_portfolio.validators.file_size_validate], verbose_name='файл3'),
        ),
        migrations.AddField(
            model_name='work',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/files/', validators=[app_portfolio.validators.file_size_validate], verbose_name='файл4'),
        ),
    ]
