# Generated by Django 4.1.6 on 2023-02-26 10:09

import app_portfolio.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0004_work_ordering_alter_work_is_active_alter_work_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/files/%Y/%m/%d/', validators=[app_portfolio.validators.file_size_validate], verbose_name='файл1'),
        ),
        migrations.AlterField(
            model_name='work',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/files/%Y/%m/%d/', validators=[app_portfolio.validators.file_size_validate], verbose_name='файл2'),
        ),
        migrations.AlterField(
            model_name='work',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/files/%Y/%m/%d/', validators=[app_portfolio.validators.file_size_validate], verbose_name='файл3'),
        ),
        migrations.AlterField(
            model_name='work',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/files/%Y/%m/%d/', validators=[app_portfolio.validators.file_size_validate], verbose_name='файл4'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/covers/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'], message='Ошибка загрузки: допускаются только файлы с расширением .jpg .png'), app_portfolio.validators.file_size_validate], verbose_name='обложка'),
        ),
    ]
