# Generated by Django 4.1.6 on 2023-02-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_static_pages', '0002_alter_staticpage_text_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=55, null=True, verbose_name='название компании')),
                ('description', models.TextField(blank=True, null=True, verbose_name='краткое описание')),
                ('email1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email 1')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email 2')),
                ('email3', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email 3')),
                ('phone_number1', models.CharField(blank=True, max_length=17, null=True, verbose_name='номер телефона 1')),
                ('phone_number2', models.CharField(blank=True, max_length=17, null=True, verbose_name='номер телефона 2')),
                ('phone_number3', models.CharField(blank=True, max_length=17, null=True, verbose_name='номер телефона 3')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='город')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='адрес')),
                ('footer_pages', models.ManyToManyField(to='app_static_pages.staticpage', verbose_name='статичные страницы для футера')),
            ],
            options={
                'verbose_name': 'настройки',
                'verbose_name_plural': 'настройки',
            },
        ),
    ]
