# Generated by Django 4.1.6 on 2023-02-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_settings', '0001_initial'),
        ('app_static_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerpagesrightset',
            name='footer_pages',
            field=models.ManyToManyField(to='app_static_pages.staticpage', verbose_name='статичные страницы для футера (справа)'),
        ),
        migrations.AddField(
            model_name='footerpagesleftset',
            name='footer_pages',
            field=models.ManyToManyField(to='app_static_pages.staticpage', verbose_name='статичные страницы для футера (слева)'),
        ),
    ]
