# Generated by Django 4.1.6 on 2023-02-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='номер телефона 1'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='номер телефона 2'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_number3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='номер телефона 3'),
        ),
    ]
