# Generated by Django 4.1.6 on 2023-02-09 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_static_pages', '0002_alter_staticpage_text_block'),
        ('app_settings', '0002_alter_sitesettings_phone_number1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_pages',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_pages',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_static_pages.staticpage', verbose_name='статичные страницы для футера'),
            preserve_default=False,
        ),
    ]
