# Generated by Django 4.1.6 on 2023-02-20 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerpagesrightset',
            name='footer_pages',
        ),
        migrations.DeleteModel(
            name='FooterPagesLeftSet',
        ),
        migrations.DeleteModel(
            name='FooterPagesRightSet',
        ),
    ]
