# Generated by Django 4.1.6 on 2023-02-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0003_remove_sitesettings_footer_pages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department1', models.CharField(blank=True, max_length=55, null=True, verbose_name='название отдела 1')),
                ('email1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email 1')),
                ('phone_number1', models.CharField(blank=True, max_length=20, null=True, verbose_name='номер телефона 1')),
                ('department2', models.CharField(blank=True, max_length=55, null=True, verbose_name='название отдела 2')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email 2')),
                ('phone_number2', models.CharField(blank=True, max_length=20, null=True, verbose_name='номер телефона 2')),
                ('department3', models.CharField(blank=True, max_length=55, null=True, verbose_name='название отдела 3')),
                ('email3', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email 3')),
                ('phone_number3', models.CharField(blank=True, max_length=20, null=True, verbose_name='номер телефона 3')),
                ('address1', models.CharField(blank=True, max_length=150, null=True, verbose_name='адрес 1')),
                ('address2', models.CharField(blank=True, max_length=150, null=True, verbose_name='адрес 2')),
                ('address3', models.CharField(blank=True, max_length=150, null=True, verbose_name='адрес 3')),
            ],
            options={
                'verbose_name': 'контакты',
                'verbose_name_plural': 'контакты',
            },
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
