# Generated by Django 4.1.6 on 2023-02-09 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0004_contactsettings_delete_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsettings',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='address3',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='department1',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='department2',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='department3',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='email1',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='email3',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='phone_number1',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='phone_number2',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='phone_number3',
        ),
        migrations.CreateModel(
            name='ContactGrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=55, null=True, verbose_name='название отдела')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='номер телефона')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='адрес')),
                ('сontact_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='app_settings.contactsettings', verbose_name='настройки контактов')),
            ],
            options={
                'verbose_name': 'группа контактов',
                'verbose_name_plural': 'группы контактов',
            },
        ),
    ]
