# Generated by Django 4.1.6 on 2023-02-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0006_companysettings_alter_contactsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysettings',
            options={'verbose_name': 'компания', 'verbose_name_plural': 'компания'},
        ),
        migrations.AlterModelOptions(
            name='contactsettings',
            options={'verbose_name': 'контакты', 'verbose_name_plural': 'контакты'},
        ),
        migrations.AddField(
            model_name='companysettings',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='адрес'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='номер телефона'),
        ),
    ]
