# Generated by Django 4.1.6 on 2023-02-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0008_footerpagesset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterPagesSet',
        ),
    ]
