# Generated by Django 4.1.6 on 2023-02-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_static_pages', '0002_alter_staticpage_text_block'),
        ('app_settings', '0010_footerpagesset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerpagesset',
            options={'verbose_name': 'статичные страницы для футера (справа)', 'verbose_name_plural': 'статичные страницы для футера (справа)'},
        ),
        migrations.AlterField(
            model_name='footerpagesset',
            name='footer_pages',
            field=models.ManyToManyField(to='app_static_pages.staticpage', verbose_name='статичные страницы для футера (справа)'),
        ),
        migrations.CreateModel(
            name='FooterPagesLeftSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_pages', models.ManyToManyField(to='app_static_pages.staticpage', verbose_name='статичные страницы для футера (слева)')),
            ],
            options={
                'verbose_name': 'статичные страницы для футера (слева)',
                'verbose_name_plural': 'статичные страницы для футера (слева)',
            },
        ),
    ]
