# Generated by Django 4.1.6 on 2023-02-12 09:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='can_invite_referrals',
            field=models.BooleanField(db_index=True, default=False, verbose_name='может приглашать рефералов'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_freelancer',
            field=models.BooleanField(db_index=True, default=False, verbose_name='является фрилансером'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79012345678'.", regex='^\\+\\d{11,15}')], verbose_name='номер телефона'),
        ),
    ]
