# Generated by Django 4.1.6 on 2023-02-12 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_customuser_referer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='реферер'),
        ),
    ]
