# Generated by Django 4.1.6 on 2023-02-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.SlugField(blank=True, max_length=55, null=True, unique=True, verbose_name='имя пользователя'),
        ),
    ]
