# Generated by Django 4.1.6 on 2023-02-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_customuser_is_core'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_freelancer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('0', 'Участник Заказчик'), ('1', 'Кандидат'), ('2', 'Участник Фрилансер')], db_index=True, default='0', max_length=30, verbose_name='статус'),
        ),
    ]
