# Generated by Django 4.1.6 on 2023-02-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_remove_customuser_is_freelancer_customuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
    ]
