# Generated by Django 4.1.6 on 2023-02-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_customuser_email_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bank_bic',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='БИК банка'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bank_correspondent_account',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Корреспондентский счет банка'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='document_issued',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Когда и кем выдан'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_core',
            field=models.BooleanField(db_index=True, default=False, verbose_name='основатель'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='payment_account',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='personal_number',
            field=models.CharField(blank=True, db_index=True, max_length=17, null=True, verbose_name='ИНН или персональный номер'),
        ),
    ]
