# Generated by Django 4.1.6 on 2023-02-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_remove_customuser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='can_invite_referrals',
        ),
    ]
