# Generated by Django 4.1.6 on 2023-02-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_remove_customuser_can_invite_referrals'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10, verbose_name='баланс'),
        ),
    ]
