# Generated by Django 4.1.6 on 2023-02-23 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_alter_customuser_bank_bic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('post', models.CharField(choices=[('CM', 'Председатель'), ('AD', 'Администратор'), ('AU', 'Ревизор'), ('TS', 'ТехПоддержка'), ('DE', 'Разработчик'), ('AC', 'Бухгалтер'), ('CF', 'Фонд потребления'), ('DF', 'Фонд развития')], db_index=True, default='TS', max_length=3, verbose_name='должность')),
            ],
            options={
                'abstract': False,
            },
            bases=('app_users.customuser',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
