# Generated by Django 4.1.6 on 2023-02-23 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(choices=[('CF', 'Фонд потребления'), ('DF', 'Фонд развития')], db_index=True, default='CF', max_length=3, verbose_name='тип фонда')),
            ],
            options={
                'verbose_name': 'фонд',
                'verbose_name_plural': 'фонды',
            },
            bases=('app_users.customuser',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
