# Generated by Django 4.1.6 on 2023-02-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_fund_delete_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fund',
        ),
    ]
