# Generated by Django 4.1.6 on 2023-02-26 10:09

import app_users.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_delete_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif'], message='Ошибка загрузки: допускаются только файлы с расширением .jpg .gif .png'), app_users.validators.avatar_size_validate]),
        ),
    ]
