# Generated by Django 4.1.6 on 2023-02-13 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, db_index=True, verbose_name='описание')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='цена')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='app_ads.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
                'ordering': ('price',),
            },
        ),
    ]
