# Generated by Django 4.1.6 on 2023-02-26 10:09

import app_ads.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ads', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, db_index=True, upload_to='category/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'svg'], message='Ошибка загрузки: допускаются только файлы с расширением .jpg .gif .png .svg'), app_ads.validators.image_size_validate], verbose_name='изображение'),
        ),
    ]
