# Generated by Django 4.1.6 on 2023-02-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ads', '0002_adv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='заголовок'),
        ),
    ]
