# Generated by Django 4.1.6 on 2023-02-13 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ads', '0003_alter_adv_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adv',
            options={'ordering': ('-created',), 'verbose_name': 'объявление', 'verbose_name_plural': 'объявления'},
        ),
    ]
