# Generated by Django 4.1.6 on 2023-02-22 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_users', '0005_alter_customuser_bank_bic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
            ],
            options={
                'verbose_name': 'счёт пользователя',
                'verbose_name_plural': 'счета пользователей',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('NR', 'Нет причины'), ('СP', 'Оплата сделки'), ('TU', 'Пополнение'), ('WD', 'Вывод'), ('1LС', 'Рефералы 1го уровня - сделка'), ('2LС', 'Рефералы 2го уровня - сделка'), ('3LС', 'Рефералы 3го уровня - сделка'), ('1LE', 'Рефералы 1го уровня - вступление'), ('2LE', 'Рефералы 2го уровня - вступление'), ('3LE', 'Рефералы 3го уровня - вступление')], default='NR', max_length=5, verbose_name='причина')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='сумма')),
                ('datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата транзакции')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='app_personal_account.personalaccount', verbose_name='лицевой счет')),
            ],
            options={
                'verbose_name': 'транзакция',
                'verbose_name_plural': 'транзакции',
                'ordering': ('-datetime',),
            },
        ),
    ]
