# Generated by Django 4.1.6 on 2023-02-22 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_personal_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='direction',
            field=models.CharField(choices=[('CRE', 'Зачисление'), ('DEB', 'Списание')], default=django.utils.timezone.now, max_length=5, verbose_name='тип операции'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reason',
            field=models.CharField(choices=[('NR', 'Нет причины'), ('СP', 'Оплата сделки'), ('TUBT', 'Пополнение переводом (вручную)'), ('WDBT', 'Вывод переводом (вручную)'), ('TU', 'Пополнение'), ('WD', 'Вывод'), ('1LС', 'Рефералы 1го уровня - сделка'), ('2LС', 'Рефералы 2го уровня - сделка'), ('3LС', 'Рефералы 3го уровня - сделка'), ('1LE', 'Рефералы 1го уровня - вступление'), ('2LE', 'Рефералы 2го уровня - вступление'), ('3LE', 'Рефералы 3го уровня - вступление')], default='NR', max_length=5, verbose_name='причина'),
        ),
    ]
