# Generated by Django 4.1.6 on 2023-02-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_personal_account', '0006_alter_transaction_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='exist',
            field=models.BooleanField(default=False),
        ),
    ]
