# Generated by Django 4.1.6 on 2023-02-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_personal_account', '0007_transaction_exist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reason',
            field=models.CharField(choices=[('NR', 'Нет причины'), ('ERR', 'Ошибка'), ('СP', 'Оплата сделки'), ('DF', 'Фонд развития - вступительный взнос'), ('CF', 'Фонд потребления - вступительный взнос'), ('TUBT', 'Пополнение переводом (вручную)'), ('WDBT', 'Вывод переводом (вручную)'), ('TU', 'Пополнение'), ('WD', 'Вывод'), ('1LС', 'Рефералы 1го уровня - сделка'), ('2LС', 'Рефералы 2го уровня - сделка'), ('3LС', 'Рефералы 3го уровня - сделка'), ('1LE', 'Рефералы 1го уровня - вступление'), ('2LE', 'Рефералы 2го уровня - вступление'), ('3LE', 'Рефералы 3го уровня - вступление')], default='NR', max_length=5, verbose_name='причина'),
        ),
    ]
